[package]
name = "test-cli-manual"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-table = "0.4.7"
rusqlite = { version = "0.28.0", features = ["bundled"] }
